version: '2'
services:
 dinghy:
   ports:
     - "3000:3000"
   links:
     - balena-wpe
   networks:
     - local
       ipv4_address: 172.20.0.5
   privileged: true
   build: ./dinghy
   restart: always
 wpe:
   networks:
     - local
       ipv4_address: 172.20.0.6     
   privileged: true
   build: ./balena-wpe
   restart: always
networks:
  local:
    driver: "bridge"
    ipam:
      config:
        - subnet: 172.20.0.0/24